### ISSUE TITLE
Arithmetic bug

### ISSUE THREAD

**Issue by leobru** [besm6/dubna#1] opened 2024-03-27 06:57 UTC
```
*name FORTRAN
*     EDIT THE PROGRAM BELOW
      program eps
      real a, b
      a = 1.
      i = 0
  10  a=a/2.
      i=i+1
      b = -1.+a
      if(b.eq.-1.) stop
      print 11,i,b,b
c Least significant digits 5 must form a neat staircase, they do not
c But on the dispak emulator, they do
  11  format(' -1.0+2**-',i2,' =',f43.40,o17)
      goto 10
      end
*no load list
*execute
*end file
```

**Comment by sergev** [comment] 2024-04-11 23:50
I've created a unit test and here is the mismatch:
```
[ RUN      ] dubna_session.epsilon
dubna/tests/fixture_session.h:98: Failure
Expected equality of these values:
  output_line
    Which is: " -1.0+2**-38 =-0.9999999999956344254314899444580078125000 4020000000000004"
  expect_line
    Which is: " -1.0+2**-38 =-0.9999999999963620211929082870483398437500 4020000000000004"
dubna/tests/fixture_session.h:98: Failure
Expected equality of these values:
  output_line
    Which is: " -1.0+2**-39 =-0.9999999999970896169543266296386718750000 4020000000000002"
  expect_line
    Which is: " -1.0+2**-39 =-0.9999999999981810105964541435241699218750 4020000000000002"
dubna/tests/fixture_session.h:98: Failure
Expected equality of these values:
  output_line
    Which is: " -1.0+2**-40 =-0.9999999999985448084771633148193359375000 4020000000000001"
  expect_line
    Which is: " -1.0+2**-40 =-0.9999999999990905052982270717620849609375 4020000000000001"
[  FAILED  ] dubna_session.epsilon (19 ms)
```

**Comment by sergev** [comment] 2024-04-12 01:29
The test can be simplified down to:
```
      print 1000, 4020000000000001b
 1000 format(f44.40)
      stop
```
On dispak it prints a valid value:
```
 -0.9999999999990905052982270717620849609375
```
On dubna it fails:
```
 -0.9999999999985448084771633148193359375000
```
The program is compiled into the following assembly code:
```
                   C*****HAЧAЛO  OПEPATOPA 1
 0001 0016                   14, VTM ,  /1000
  -                            , ITS ,  14
 0002                        13, VJM ,  FT*571
  -
 0003 0020                   14, VTM ,= 40200000 00000001
  -                            , ITS ,  14
 0004                        13, VJM ,  FT*002
  -
 0005                        13, VJM ,  FT*003
                   C*****HAЧAЛO  OПEPATOPA 2
  -
 0006                        13, VJM ,  STOP*
```
Four routines are called:
- `FT*571` - start formatted output
- `FT*002` - print next value
- `FT*003` - finish formatted output
- `STOP*` - terminate the program

**Comment by sergev** [comment] 2024-04-13 01:50
I've reproduced this bug on `dispak` simulator. So it's not about wrong arithmetic of the simulator. It's a bad implementation of floating point formatted output in that version of Fortran Dubna. Try attached file [epsilon.txt](https://github.com/besm6/dubna/files/14964886/epsilon.txt).
```
$ dispak epsilon.dub 
                                                      13.04.24 М1

  М О Н И Т О Р-8 0  (3.7)   25.09.84*       (  МС " Д У Б Н А " ИАЭ  )             ШИФР    419999000000







                    ЖЖЖЖ  ЖЖЖЖ   ЖЖЖ   ЖЖЖ  Ж      ЖЖЖ  Ж   Ж
                    Ж     Ж   Ж Ж       Ж   Ж     Ж   Ж ЖЖ  Ж
                    ЖЖЖ   Ж   Ж  ЖЖЖ    Ж   Ж     Ж   Ж Ж Ж Ж
                    Ж     Ж   Ж     Ж   Ж   Ж     Ж   Ж Ж  ЖЖ
                    Ж     ЖЖЖЖ      Ж   Ж   Ж     Ж   Ж Ж   Ж
                    Ж     Ж     Ж   Ж   Ж   Ж     Ж   Ж Ж   Ж
                    ЖЖЖЖЖ Ж      ЖЖЖ   ЖЖЖ  ЖЖЖЖЖ  ЖЖЖ  Ж   Ж








*NАМЕ ЕРSILОN
           *NО LISТ
           *МАDLЕN
           *FОRТRАN
           *NО LОАD LISТ
           *ЕХЕСUТЕ
 -0.9999999999985448084771633148193359375000
 КОНЕЦ ЗАДАЧИ
 00411: 00 074 0000	*74
```

**Comment by sergev** [comment] 2024-04-13 01:52
So I'm closing this issue as not a bug.

**Closed as completed by sergev** 2024-04-13 01:52 UTC
Labels: bug
